#AGTCACTTAATTTATGACACATGACAAAGAGAAAAGATGGCCTTTTCAGAAAAGGTACTGGGAGAACTGAACTCTCCATAAGGGAAAAAAATGAAACTTTTATCACAAATCATATCGAGAAATCAGTGTTAGGTAGATCATAGATGTA
#ACTGTGTTGCCCAGGCTGGTCTCAAACTCCTGGCTTCAGAATCATCCTGCCTTGGCCTCCAAAAGTGCTGGGATTACAGGTGTGAGCCACCACACCCGGCCTGTGTTCCCTCTTGATTAGGCTTCAGATGTTTTTCCAAGTTCATCTT
#AAGTCTGAGATTTTAGTGTATTCATCATCCAAGTAGTATACATTGTACCCAATATGTAGTGTTTGTTTGTTTGAGACAGAGTCTTGCTCTGTCGCCAGGCTGGGGTGCAATGGCATGATCTTGGCTCACTGCAACCTCCATCTCCCCA

@dis_seq=<STDIN>;
chomp(@dis_seq);
$left=$ARGV[0];
$right=$ARGV[1];
sub get_long_seq
{
	my ($subseq,@seq_long,$dir)=@_;
	foreach $i (@seq_long)
	{
		if($dir eq 'left')
		{
			$subseq_t=substr($subseq,0,15);
			if($i=~/(^.*)$subseq_t/)
			{
				$ex_seq_t=$1;
				&sub_long_seq($ex_seq_t,@seq_long);
			}
		}
	}
}

